import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parse } from "yaml";

const schemaText=readFileSync(new URL("../gpt-action/openapi.yaml",import.meta.url),"utf8");
const instructions=readFileSync(new URL("../gpt-action/CFI_GPT_INSTRUCTIONS.md",import.meta.url),"utf8");

test("GPT Action OpenAPI parses and preserves production operation IDs",()=>{const schema=parse(schemaText);assert.equal(schema.openapi,"3.1.0");assert.equal(schema.paths["/api/status"].get.operationId,"cfiGetStatus");assert.equal(schema.paths["/api/predict"].post.operationId,"cfiPredictMatch");assert.equal(schema.paths["/api/prediction-history"].get.operationId,"cfiGetPredictionHistory");assert.equal(schema.paths["/api/results"].get.operationId,"cfiGetResults");assert.equal(schema.paths["/api/collect-results"].post.operationId,"cfiCollectResults");const request=schema.paths["/api/predict"].post.requestBody.content["application/json"].schema;assert.ok(request.properties.target_date);assert.deepEqual(request.required,["home","away"]);const prediction=schema.components.schemas.Prediction;assert.equal(prediction.additionalProperties,true);assert.deepEqual(prediction.required,["sixTargetMatrix","renderedReport","presentationContract"]);assert.equal(schema.components.schemas.SixTargetMatrix.properties.contract.const,"CFI_2_METHODS_X_6_TARGETS_V1");assert.equal(schema.components.schemas.PresentationContract.properties.mode.const,"RENDER_RENDERED_REPORT_VERBATIM");});

test("GPT instructions require canonical 2 methods x 6 targets contract",()=>{for(const token of ["cfiPredictMatch","CFI_2_METHODS_X_6_TARGETS_V1","sixTargetMatrix.verification.complete","renderedReport","RENDER_RENDERED_REPORT_VERBATIM","Method A","Method B","FINAL","Top-3 HT","Top-3 FT","RUNTIME CONTRACT ERROR","Never collapse Top-3 HT or Top-3 FT into a single list"])assert.match(instructions,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(instructions,/Never reconstruct/);assert.match(instructions,/Never search File Library/);});

test("production config points at active V55 diversity guard",()=>{const worker=readFileSync(new URL("../cloudflare-worker/src/index-v55.ts",import.meta.url),"utf8");const config=readFileSync(new URL("../wrangler.jsonc",import.meta.url),"utf8");assert.match(config,/index-v55\.ts/);assert.match(worker,/CFI_FINAL_V5\.2\.5/);assert.match(worker,/CFI_SIX_TARGET_RUNTIME_V1\.4/);assert.match(worker,/CFI_MATCH_DIVERSITY_GUARD_V1/);assert.match(worker,/thresholdGlobalPriorDirectShrinkage:false/);assert.match(worker,/sixTargetMatrix/);assert.match(worker,/renderedReport/);assert.match(worker,/TOP-3 HT — PRIMARY TARGET/);assert.match(worker,/TOP-3 FT — PRIMARY TARGET/);});

test("result and settlement bridge remain preserved",()=>{const resultWorker=readFileSync(new URL("../cloudflare-worker/src/index-v47.ts",import.meta.url),"utf8");const compatWorker=readFileSync(new URL("../cloudflare-worker/src/index-v48.ts",import.meta.url),"utf8");assert.match(resultWorker,/\/api\/prediction-history/);assert.match(resultWorker,/\/api\/results/);assert.match(resultWorker,/\/api\/collect-results/);assert.match(compatWorker,/legacyResultBridge/);assert.match(compatWorker,/action:'COLLECT'/);});
