import test from 'node:test';
import assert from 'node:assert/strict';
import {runGroupAProspectiveCapture,loadGroupAProspectiveLiveInputs,GROUP_A_PROSPECTIVE_RUNNER_V1} from '../research/group-a-prospective-runner-v1.mjs';

function corpus(){const fixtures=[];for(let n=0;n<24;n+=1){const d=new Date(Date.UTC(2026,6,20+n)).toISOString().slice(0,10);for(const [j,[hid,aid,home,away]] of [[0,['a','c','Alpha','Gamma']],[1,['b','d','Beta','Delta']]]){const fh=(n+j)%4,fa=(n+2*j)%3;fixtures.push({fixture_id:`h-${n}-${j}`,match_date:d,home_team_id:hid,away_team_id:aid,home_team:home,away_team:away,ht_home:Math.min(fh,n%2),ht_away:Math.min(fa,(n+1)%2),ft_home:fh,ft_away:fa,status:'CANONICAL',competition_key:'england:e1',competition_name:'England Championship',country:'England',season:'2026-27',competition_segment:'MID_PRO'});}}return {fixtures};}
const features={baselineCommitSha:'8ca9a3634f536f2f838135df062f5bbbf7da0d9a',strengths:[{team_id:'a',as_of_date:'2026-08-19',strict_prior:true,attack_index:.7,defense_index:-.2,net_strength:.5,confidence:.9,competition_key:'england:e1',segment_v2:'M|SENIOR|MID_PRO'},{team_id:'b',as_of_date:'2026-08-19',strict_prior:true,attack_index:.2,defense_index:.1,net_strength:-.1,confidence:.85,competition_key:'england:e1',segment_v2:'M|SENIOR|MID_PRO'}]};
const fixture={fixture_id:'vf-1',target_date:'2026-09-02',kickoff_at:'2026-09-02T18:45:00Z',home_team:'Alpha',away_team:'Beta',canonical_home_team_id:'a',canonical_away_team_id:'b',competition:'E1',source_name:'Football-Data',source_provenance:{provider:'football-data',sourceDivision:'E1'},verification_status:'VERIFIED'};
const market={market_snapshot_id:'m-1',fixture_id:null,verified_fixture_id:'vf-1',captured_at:'2026-09-02T15:00:00Z',kickoff_at:'2026-09-02T18:45:00Z',bookmaker:'BOOK',market_family:'1X2',period:'FT',line:null,odds_home:2.2,odds_draw:3.3,odds_away:3.6,odds_over:null,odds_under:null,source_name:'verified-feed',source_url:null,source_provenance:{ref:'m1'},is_closing:false,research_only:true};
const profile={competition_key:'england:e1',competition_name:'England Championship',country:'England',segment:'MID_PRO',gender:'M',age_class:'SENIOR',professional_level:'PRO',source:'profile',confidence:1};
const hfSummary={version:'CFI_HF_GROUP_A_SHADOW_V1',frozenStateVersion:'CFI_GROUP_A_FROZEN_PROSPECTIVE_STATE_V1',trainedThrough:'2026-08-19',strictPrior:true,noReconstruction:true,decisionUse:false,productionMutationAllowed:false,selectedCandidates:['OPPONENT_STRENGTH_ARM_V1','HIERARCHICAL_LEAGUE_SEGMENT_CALIBRATION_V1'],frozenLearners:{OPPONENT_STRENGTH_ARM_V1:{stateVersion:'CFI_GROUP_A_FROZEN_PROSPECTIVE_STATE_V1',trainedThrough:'2026-08-19',ht:{n:1000,beta:[.01,.1,-.05,.08]},ft:{n:1000,beta:[.02,.2,-.1,.16]}},HIERARCHICAL_LEAGUE_SEGMENT_CALIBRATION_V1:{stateVersion:'CFI_GROUP_A_FROZEN_PROSPECTIVE_STATE_V1',trainedThrough:'2026-08-19',globalHt:{n:1000,h:.06,a:-.02},globalFt:{n:1000,h:.12,a:-.04},segmentHt:{MID_PRO:{n:500,h:.1,a:.02}},segmentFt:{MID_PRO:{n:500,h:.2,a:.01}},segmentPriorWeight:500}}};
function reader({fixtures=[fixture],markets=[market],profiles=[profile]}={}){return {async readAll(path){if(path.startsWith('cfi_living_verified_fixtures?'))return fixtures;if(path.startsWith('cfi_market_snapshots?'))return markets;if(path.startsWith('cfi_competition_profiles?'))return profiles;throw new Error(`UNEXPECTED_PATH:${path}`);}};}

test('runner contract is bounded research-only and has no settlement writer',()=>{assert.equal(GROUP_A_PROSPECTIVE_RUNNER_V1.productionMutationAllowed,false);assert.equal(GROUP_A_PROSPECTIVE_RUNNER_V1.decisionUse,false);assert.equal(GROUP_A_PROSPECTIVE_RUNNER_V1.settlementWriterIncluded,false);assert.equal(GROUP_A_PROSPECTIVE_RUNNER_V1.defaultMaxFixtures,20);assert.equal(GROUP_A_PROSPECTIVE_RUNNER_V1.maxFixtureCap,100);});

test('live input loader reads only future verified fixtures and non-closing FT 1X2 research markets',async()=>{const calls=[];const r={async readAll(path){calls.push(path);if(path.startsWith('cfi_living_verified_fixtures?'))return [fixture];if(path.startsWith('cfi_market_snapshots?'))return [market];if(path.startsWith('cfi_competition_profiles?'))return [profile];return [];}};const out=await loadGroupAProspectiveLiveInputs({reader:r,nowIso:'2026-09-02T16:30:00Z'});assert.equal(out.fixtures.length,1);assert.match(calls[0],/verification_status=eq\.VERIFIED/);assert.match(calls[0],/kickoff_at=gt\./);assert.match(calls[1],/market_family=eq\.1X2/);assert.match(calls[1],/period=eq\.FT/);assert.match(calls[1],/is_closing=eq\.false/);assert.match(calls[1],/research_only=eq\.true/);});

test('dry run produces both selected candidate predictions without any writer',async()=>{const out=await runGroupAProspectiveCapture({corpus:corpus(),featureBundle:features,hfSummary,reader:reader(),writer:null,nowIso:'2026-09-02T16:30:00Z',maxFixtures:1,write:false});assert.equal(out.mode,'DRY_RUN');assert.equal(out.consideredFixtures,1);assert.equal(out.capturedDecisions,0);assert.equal(out.dryRunReady,2);assert.equal(out.results.length,2);assert.deepEqual(out.results.map(x=>x.modelName).sort(),['HIERARCHICAL_LEAGUE_SEGMENT_CALIBRATION_V1','OPPONENT_STRENGTH_ARM_V1']);assert.equal(out.productionMutationAllowed,false);assert.equal(out.settlementWriterIncluded,false);});

test('write mode calls existing snapshot/decision writer once per candidate and nothing else',async()=>{const seen={snapshots:0,decisions:0};const w={async persistSnapshot(plan){seen.snapshots+=1;return {...plan,snapshot_id:`rp-${seen.snapshots}`,idempotent:false}},async persistDecision(plan){seen.decisions+=1;return {...plan,decision_snapshot_id:`d-${seen.decisions}`,idempotent:false}}};const out=await runGroupAProspectiveCapture({corpus:corpus(),featureBundle:features,hfSummary,reader:reader(),writer:w,nowIso:'2026-09-02T16:30:00Z',maxFixtures:1,write:true});assert.equal(out.mode,'WRITE_RESEARCH_ONLY');assert.equal(out.capturedDecisions,2);assert.equal(seen.snapshots,2);assert.equal(seen.decisions,2);assert.equal(out.results.every(x=>x.settlementPath==='EXISTING_APPEND_ONLY_CFI_MARKET_DECISION_SETTLEMENTS'),true);});

test('missing market or unresolved competition is blocked, not fabricated',async()=>{const noMarket=await runGroupAProspectiveCapture({corpus:corpus(),featureBundle:features,hfSummary,reader:reader({markets:[]}),nowIso:'2026-09-02T16:30:00Z',maxFixtures:1,write:false});assert.equal(noMarket.dryRunReady,0);assert.ok(noMarket.blocked[0].reason.includes('PREKICKOFF_1X2_FT_MARKET_REQUIRED'));const noProfile=await runGroupAProspectiveCapture({corpus:corpus(),featureBundle:features,hfSummary,reader:reader({profiles:[]}),nowIso:'2026-09-02T16:30:00Z',maxFixtures:1,write:false});assert.equal(noProfile.dryRunReady,0);assert.ok(noProfile.blocked[0].reason.includes('COMPETITION_PROFILE_REQUIRED'));});

test('HF learner boundary drift fails before any live input can be used',async()=>{const bad=structuredClone(hfSummary);bad.frozenLearners.OPPONENT_STRENGTH_ARM_V1.trainedThrough='2026-08-20';await assert.rejects(()=>runGroupAProspectiveCapture({corpus:corpus(),featureBundle:features,hfSummary:bad,reader:reader(),nowIso:'2026-09-02T16:30:00Z',write:false}),/FROZEN_LEARNER_REQUIRED/);});
