import test from 'node:test';
import assert from 'node:assert/strict';
import { runGroupAFullSuiteV1, GROUP_A_CHALLENGERS } from '../research/group-a-full-suite-v1.mjs';

const teams=[['a','Alpha'],['b','Beta'],['c','Gamma'],['d','Delta']];
const iso=n=>{const d=new Date(Date.UTC(2025,0,1+n));return d.toISOString().slice(0,10)};
function data(days=70){const fixtures=[],strengths=[];for(let n=0;n<days;n++){const date=iso(n),comp=n%2?'comp:1':'comp:2',prev=n%2?'comp:2':'comp:1';const pairs=n%2?[[0,1],[2,3]]:[[0,2],[1,3]];for(let j=0;j<2;j++){const [hi,ai]=pairs[j],[hid,h]=teams[hi],[aid,a]=teams[ai],hg=(n+j)%4,ag=(n+2*j)%3,hh=Math.min(hg,(n+j)%2),ha=Math.min(ag,(n+j+1)%2);fixtures.push({fixture_id:`f-${n}-${j}`,match_date:date,home_team_id:hid,away_team_id:aid,home_team:h,away_team:a,ht_home:hh,ht_away:ha,ft_home:hg,ft_away:ag,status:'CANONICAL',competition_key:comp,competition_name:'Test League',country:'Testland',season:'2024-25',competition_segment:n%3?'MID_PRO':'ELITE_PRO'});}for(const [id,name] of teams){const sign=id==='a'?1:id==='b'?.3:id==='c'?-.4:-1;strengths.push({team_id:id,team_name:name,as_of_date:date,attack_index:sign*.7,defense_index:-sign*.4,net_strength:sign,confidence:.9,strict_prior:true,competition_key:comp,segment_v2:n%3?'M|SENIOR|MID':'M|SENIOR|ELITE',feature_version:'TEST'});}strengths.push({team_id:`dummy-${n}-1`,team_name:'Dummy One',as_of_date:date,attack_index:0,defense_index:0,net_strength:-.8,confidence:1,strict_prior:true,competition_key:prev,segment_v2:'M|SENIOR|MID',feature_version:'TEST'});strengths.push({team_id:`dummy-${n}-2`,team_name:'Dummy Two',as_of_date:date,attack_index:0,defense_index:0,net_strength:.8,confidence:1,strict_prior:true,competition_key:prev,segment_v2:'M|SENIOR|MID',feature_version:'TEST'});}return {corpus:{fixtures},features:{baselineCommitSha:'518dfb57aafc8428e09b3ec84e440146c839a19e',strengths}};}
const opts={skipSourceLock:true,minTeamPrior:3,minOnlineSamples:0,historyCap:8,evaluationStart:'2025-01-10',evaluationEnd:'2025-03-20'};

test('full Group A suite runs all four challengers on one locked Multi-Market contract',()=>{const {corpus,features}=data(),a=runGroupAFullSuiteV1(corpus,features,opts),b=runGroupAFullSuiteV1(corpus,features,opts);assert.equal(a.strictPrior,true);assert.equal(a.sameDateLeakage,false);assert.equal(a.futureLeakage,false);assert.equal(a.decisionUse,false);assert.equal(a.productionMutationAllowed,false);assert.equal(a.baseline.engine,'CFI_FINAL_V5.3.0');assert.equal(a.baseline.runtime,'CFI_PRIMARY_TOP1_RUNTIME_V2');assert.equal(a.baseline.primaryContract,'CFI_2_METHODS_X_6_TARGETS_V2');assert.equal(a.baseline.multiMarketVersion,'CFI_MULTI_MARKET_V1');assert.equal(a.determinism.fingerprint,b.determinism.fingerprint);for(const name of GROUP_A_CHALLENGERS){const x=a.challengers[name];assert.ok(x);assert.equal(x.decisionUse,false);assert.equal(x.productionMutationAllowed,false);assert.equal(x.promotionDecision,'HOLD');assert.equal(x.shadowEligible,false);assert.ok(x.coverage.eligible>0||name==='PROMOTION_RELEGATION_STRENGTH_BRIDGE_V1');assert.equal(x.metrics.scoreline.baseline,undefined);assert.ok(x.metrics.oneXTwo.ht.n>0||name==='PROMOTION_RELEGATION_STRENGTH_BRIDGE_V1');assert.ok(x.hardBlockers.includes('BASELINE_FULL_SCORE_GRID_NOT_EXPOSED_FOR_PAIRED_SCORELINE_LOGLOSS'));}}
);

test('clean Group A candidates expose deterministic frozen prospective learner state',()=>{const {corpus,features}=data(),a=runGroupAFullSuiteV1(corpus,features,opts),b=runGroupAFullSuiteV1(corpus,features,opts);const opp=a.challengers.OPPONENT_STRENGTH_ARM_V1.learner,hier=a.challengers.HIERARCHICAL_LEAGUE_SEGMENT_CALIBRATION_V1.learner;assert.equal(opp.stateVersion,'CFI_GROUP_A_FROZEN_PROSPECTIVE_STATE_V1');assert.equal(hier.stateVersion,'CFI_GROUP_A_FROZEN_PROSPECTIVE_STATE_V1');assert.equal(opp.trainedThrough,'2026-08-19');assert.equal(hier.trainedThrough,'2026-08-19');assert.equal(opp.ht.beta.length,4);assert.equal(opp.ft.beta.length,4);assert.ok(hier.globalHt.n>0);assert.ok(hier.globalFt.n>0);assert.equal(hier.segmentPriorWeight,500);assert.ok(Object.keys(hier.segmentHt).length>0);assert.ok(Object.keys(hier.segmentFt).length>0);assert.deepEqual(opp,b.challengers.OPPONENT_STRENGTH_ARM_V1.learner);assert.deepEqual(hier,b.challengers.HIERARCHICAL_LEAGUE_SEGMENT_CALIBRATION_V1.learner);});

test('non-strict strength fails closed',()=>{const {corpus,features}=data(15);features.strengths[3]={...features.strengths[3],strict_prior:false};assert.throws(()=>runGroupAFullSuiteV1(corpus,features,opts),/GROUP_A_NON_STRICT_PRIOR_STRENGTH_ROW/)});

test('holdout fixtures fail closed',()=>{const {corpus,features}=data(15);corpus.fixtures.push({...corpus.fixtures[0],fixture_id:'holdout',match_date:'2026-08-20'});assert.throws(()=>runGroupAFullSuiteV1(corpus,features,opts),/GROUP_A_HOLDOUT_LEAKAGE/)});

test('feature baseline lineage drift fails closed',()=>{const {corpus,features}=data(15);features.baselineCommitSha='deadbeef';assert.throws(()=>runGroupAFullSuiteV1(corpus,features,opts),/GROUP_A_FEATURE_BASELINE_LINEAGE_DRIFT/)});
