import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {handleMatchContext} from '../src/runtime/match-context.ts';
const env={CFI_DB_BASE_URL:'https://example.test/functions/v1/cfi-db',CFI_DB_KEY:'test-only'};
const row={fixture_id:'f1',match_date:'2026-09-14',home_team_id:'h',away_team_id:'a',home_name:'Home',away_name:'Away',ft_home:2,ft_away:1,ht_home:null,ht_away:null,provenance:[{source_label:'canonical'}]};
const evidence=()=>({status:'OK',identity:{homeFound:true,awayFound:true,homeTeamId:'h',awayTeamId:'a',homeCanonical:'Home',awayCanonical:'Away'},temporalAudit:{verified:true,targetDate:'2026-09-16',maxEvidenceDate:'2026-09-14',futureEvidenceCount:0,sameDateEvidenceCount:0},fixtures:{home:[{...row}],away:[{...row}],h2h:[{...row}]}});
const req=(body:any={home:'Home',away:'Away',target_date:'2026-09-16'})=>new Request('https://cfi.test/api/match-context',{method:'POST',body:JSON.stringify(body)});
async function run(t:any,b:any,status=200){t.mock.method(globalThis,'fetch',async()=>Response.json(b,{status}));return handleMatchContext(req(),env)}
test('production entrypoint routes context before legacy fallback',async()=>{const s=await readFile(new URL('../cloudflare-worker/src/index-gpt-core-v5.ts',import.meta.url),'utf8');assert.match(s,/if\(url.pathname==='\/api\/match-context'\)return handleMatchContext\(request,env\)/)});
test('real BigDB shape yields read-only context, correct perspective and unknown HT',async t=>{let captured:any;t.mock.method(globalThis,'fetch',async(u:any,o:any)=>{captured={url:String(u),...o};return Response.json(evidence())});const r=await handleMatchContext(req(),env),b:any=await r.json();assert.equal(r.status,200);assert.equal(b.home.avgGoalsFor,2);assert.equal(b.away.avgGoalsFor,1);assert.equal(b.home.avgHtGoalsFor,null);assert.equal(b.home.recent[0].ht,null);assert.equal(b.home.bttsRate,100);assert.deepEqual(b.home.form,['W']);assert.deepEqual(b.away.form,['L']);assert.equal(b.readOnly,true);assert.equal(captured.headers['x-cfi-key'],'test-only');assert.match(captured.url,/cfi-bigdb-retrieval$/);assert.equal(captured.signal instanceof AbortSignal,true);assert.deepEqual(JSON.parse(captured.body),{home:'Home',away:'Away',target_date:'2026-09-16'})});
test('invalid JSON, date, missing credentials and method return JSON without fetch',async t=>{t.mock.method(globalThis,'fetch',async()=>{throw Error('unexpected fetch')});for(const [r,e,status] of [[new Request('https://x',{method:'POST',body:'bad'}),env,400],[req({home:'H',away:'A',target_date:'2026-02-30'}),env,400],[req(),{},503],[new Request('https://x'),env,405]] as const){const res=await handleMatchContext(r,e);assert.equal(res.status,status);assert.ok((await res.json() as any).error)}});
test('HTML upstream is wrapped as JSON and upstream auth is not weakened',async t=>{t.mock.method(globalThis,'fetch',async()=>new Response('Not Found',{status:404}));const r=await handleMatchContext(req(),env);assert.equal(r.status,502);assert.equal((await r.json() as any).error,'BIGDB_NON_JSON')});
test('same-day evidence blocks even if upstream audit claims verified',async t=>{const b=evidence();b.fixtures.home[0].match_date='2026-09-16';const r=await run(t,b);assert.equal(r.status,422);assert.equal((await r.json() as any).error,'STRICT_PRIOR_EVIDENCE_INVALID')});
test('unresolved identity, self match and wrong team evidence fail closed',async t=>{for(const kind of ['unresolved','self','wrong']){const b=evidence();if(kind==='unresolved')b.identity.homeFound=false;if(kind==='self')b.identity.awayTeamId='h';if(kind==='wrong')b.fixtures.home[0].home_team_id='other';const r=await run(t,b);assert.equal(r.status,422);t.mock.restoreAll()}});
test('missing exact history never becomes a fabricated zero-score sample',async t=>{const b=evidence();b.fixtures.home=[];const r=await run(t,b);assert.equal(r.status,422);assert.equal((await r.json() as any).error,'ZERO_EXACT_TEAM_EVIDENCE')});
test('upstream timeout returns bounded JSON failure',async t=>{t.mock.method(globalThis,'fetch',async()=>{throw new DOMException('timeout','TimeoutError')});const r=await handleMatchContext(req(),env);assert.equal(r.status,504);assert.equal((await r.json() as any).error,'BIGDB_TIMEOUT')});
