import base from './index-v44';

type Env={AI?:Ai;CFI_DB_BASE_URL?:string;CFI_DB_KEY?:string};
type Fixture={matchDate:string;homeTeam:string;awayTeam:string;ht?:{home:number;away:number}|null;ft?:{home:number;away:number}|null;sourceType?:string;sourceLabel?:string};

function toDataUri(file:File,bytes:ArrayBuffer){let bin='';const u8=new Uint8Array(bytes);for(let i=0;i<u8.length;i+=0x8000)bin+=String.fromCharCode(...u8.subarray(i,i+0x8000));return `data:${file.type||'image/jpeg'};base64,${btoa(bin)}`}
function parseJson(s:string){const f=s.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];const r=(f||s).trim();try{return JSON.parse(r)}catch{}const a=r.indexOf('{'),b=r.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(r.slice(a,b+1));throw new Error('VISION_JSON_PARSE_FAILED')}
function validPair(x:any){return x==null||(Number.isInteger(x.home)&&Number.isInteger(x.away)&&x.home>=0&&x.away>=0)}
function clean(rows:any[]):Fixture[]{const out:Fixture[]=[];for(const r of rows||[]){if(typeof r?.matchDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(r.matchDate))continue;if(typeof r?.homeTeam!=='string'||typeof r?.awayTeam!=='string')continue;if(!validPair(r.ht)||!validPair(r.ft))continue;if(r.ht&&r.ft&&(r.ht.home>r.ft.home||r.ht.away>r.ft.away))continue;out.push({matchDate:r.matchDate,homeTeam:r.homeTeam.trim(),awayTeam:r.awayTeam.trim(),ht:r.ht??null,ft:r.ft??null,sourceType:'SCREENSHOT',sourceLabel:'user-upload-auto'});}return out}
async function readImage(env:Env,file:File){if(!env.AI)return{status:'AI_BINDING_REQUIRED',fixtures:[],target:null};const bytes=await file.arrayBuffer();if(bytes.byteLength>6*1024*1024)return{status:'FILE_TOO_LARGE',fixtures:[],target:null};const image=toDataUri(file,bytes);const question=`You are CFI Smart Intake. The user uploads football screenshots WITHOUT labeling HOME/AWAY/H2H. Identify the target match if visibly supported and extract only safe fixture rows. Return strict JSON only: {"target":{"home":"team","away":"team","confidence":0.0}|null,"fixtures":[{"matchDate":"YYYY-MM-DD","homeTeam":"visible name","awayTeam":"visible name","ht":{"home":0,"away":0}|null,"ft":{"home":0,"away":0}|null}]}. Never invent dates/scores. Missing HT/FT is null. Ignore aggregate-only trends. target must be the current/scheduled/focus matchup visibly shown, not an arbitrary historical row.`;const response:any=await env.AI.run('@cf/moondream/moondream3.1-9B-A2B',{task:'query',image,question,reasoning:false,stream:false,temperature:0,max_tokens:3500} as any);const parsed=parseJson(String(response?.answer??response?.result??''));return{status:'OK',target:parsed?.target??null,fixtures:clean(parsed?.fixtures||[]),file:file.name}}
async function merge(env:Env,fixtures:Fixture[]){if(!fixtures.length)return{status:'NO_SAFE_FIXTURES',counters:{rows:0}};if(!env.CFI_DB_BASE_URL)return{status:'CONFIG_REQUIRED'};const url=env.CFI_DB_BASE_URL.replace(/\/cfi-db\/?$/,'/cfi-screenshot-merge');const headers:Record<string,string>={'content-type':'application/json',accept:'application/json'};if(env.CFI_DB_KEY)headers['x-cfi-key']=env.CFI_DB_KEY;const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({fixtures})});const text=await res.text();let body:any=text;try{body=JSON.parse(text)}catch{}return{status:res.ok?'OK':'MERGE_HTTP_ERROR',httpStatus:res.status,body}}
function chooseTarget(cands:any[]){const good=cands.filter(x=>x&&typeof x.home==='string'&&typeof x.away==='string');if(!good.length)return null;const map=new Map<string,{home:string;away:string,score:number,count:number}>();for(const x of good){const k=x.home.trim().toLowerCase()+'|'+x.away.trim().toLowerCase();const cur=map.get(k)||{home:x.home.trim(),away:x.away.trim(),score:0,count:0};cur.score+=Number(x.confidence||0.6);cur.count++;map.set(k,cur)}return [...map.values()].sort((a,b)=>(b.score+b.count)-(a.score+a.count))[0]||null}
function classify(fixtures:Fixture[],target:any){const c={HOME:0,AWAY:0,H2H:0,RELATED:0};if(!target)return c;const H=target.home.toLowerCase(),A=target.away.toLowerCase();for(const f of fixtures){const h=f.homeTeam.toLowerCase(),a=f.awayTeam.toLowerCase();const hasH=h===H||a===H,hasA=h===A||a===A;if(hasH&&hasA)c.H2H++;else if(hasH)c.HOME++;else if(hasA)c.AWAY++;else c.RELATED++;}return c}

const UI=`<div class="card" id="smart-intake" style="margin-top:14px"><div class="title">SMART IMAGE INTAKE — CHỈ CẦN NHẬP ẢNH</div><div class="small" style="margin-bottom:12px">Không cần phân loại HOME / AWAY / H2H. CFI tự đọc ảnh, nhận diện trận mục tiêu, tự điền HOME & AWAY, phân loại lịch sử HOME/AWAY/H2H, đối chiếu Persistent DB rồi chạy dự đoán.</div><label class="uploadbox" style="display:grid;gap:8px"><b>📸 Chọn tất cả ảnh trận đấu</b><span>Có thể chọn nhiều ảnh cùng lúc</span><input id="smartImages" type="file" accept="image/*" multiple></label><div class="actions"><button class="btn go" id="smartRun" onclick="runSmartIntake()">🧠 CFI TỰ NHẬN DIỆN & PHÂN TÍCH</button></div><div class="small" id="smartResult" style="margin-top:10px">Chưa có ảnh.</div></div>`;
const SCRIPT=`<script>async function runSmartIntake(){const files=document.getElementById('smartImages').files;if(!files.length){smartResult.textContent='Hãy chọn ít nhất 1 ảnh.';return}const fd=new FormData();for(const f of files)fd.append('IMAGES',f,f.name);smartRun.disabled=true;smartResult.textContent='CFI đang nhận diện trận mục tiêu → phân loại HOME/AWAY/H2H → hợp nhất DB → dự đoán…';try{const r=await fetch('/api/smart-image-intake',{method:'POST',body:fd});const d=await r.json();if(d.target?.home&&d.target?.away){document.getElementById('home').value=d.target.home;document.getElementById('away').value=d.target.away}const c=d.classified||{},m=d.merge?.body?.counters||d.merge?.body||d.merge?.counters||{};smartResult.innerHTML='<b>Target:</b> '+(d.target?d.target.home+' vs '+d.target.away:'AMBIGUOUS')+'<br><b>Auto-classify:</b> HOME '+(c.HOME||0)+' · AWAY '+(c.AWAY||0)+' · H2H '+(c.H2H||0)+' · RELATED '+(c.RELATED||0)+'<br><b>Merge:</b> '+(d.merge?.status||'—')+' · NEW '+(m.NEW??'—')+' · DUP '+(m.DUPLICATE_COMPATIBLE??'—')+' · COMPLEMENTARY '+(m.COMPLEMENTARY??'—')+' · CONFLICT '+(m.CONFLICT??'—')+' · REJECTED '+(m.REJECTED??'—');if(d.target&&d.merge?.status==='OK'&&typeof predict==='function')setTimeout(()=>predict(),500)}catch(e){smartResult.textContent='Smart intake error: '+e.message}finally{smartRun.disabled=false}}</script>`;

export default{async fetch(request:Request,env:Env,ctx:ExecutionContext){const url=new URL(request.url);if(url.pathname==='/api/smart-image-intake'&&request.method==='POST'){try{const form=await request.formData();const files=form.getAll('IMAGES').filter((x):x is File=>x instanceof File).slice(0,12);const fixtures:Fixture[]=[];const targets:any[]=[];const details:any[]=[];for(const file of files){const r:any=await readImage(env,file);fixtures.push(...(r.fixtures||[]));if(r.target)targets.push(r.target);details.push({file:file.name,status:r.status,fixtures:r.fixtures?.length||0,target:r.target||null})}const unique=Array.from(new Map(fixtures.map(f=>[`${f.matchDate}|${f.homeTeam}|${f.awayTeam}`,f])).values());const target=chooseTarget(targets);const classified=classify(unique,target);const merged=await merge(env,unique);return Response.json({status:'OK',target,classified,canonicalCandidates:unique.length,details,merge:merged})}catch(e:any){return Response.json({status:'ERROR',error:String(e?.message||e)},{status:500})}}const res=await base.fetch(request,env,ctx);if(url.pathname!=='/'||!String(res.headers.get('content-type')).includes('text/html'))return res;let html=await res.text();html=html.replaceAll('CFI v4.4','CFI v4.5');html=html.replace(/<div class="card" id="image-intake"[\s\S]*?<div class="markets">/,UI+'<div class="markets">');html=html.replace('</body>',SCRIPT+'</body>');return new Response(html,{status:res.status,headers:res.headers})}} satisfies ExportedHandler<Env>;
